### ISSUE TITLE
[Bug] Maximizing the window covers the taskbar

### ISSUE THREAD

**Issue by NxDs** [KnowledgeCanvas/knowledge#95]
On Windows (tested on Win10) clicking on the button to maximize the window will resize Knowledge to fit the whole screen covering the taskbar as well, this does not happen when using Window's window snapping feature (dragging the Knowledge window to the top edge of the screen)

**Comment by RobRoyce** [comment]
This is actually a known issue and is due to the way Electron handles the `window.maximize()` method.

I think it will be more work than it's worth to try and address this issue, so I'm going to close this issue with the following note: one alternative is to just double click the title bar instead of clicking the maximize button.

If someone else wants to figure out how to achieve the desired functionality, please feel free.
